### ISSUE TITLE
Presenter 的复用问题

### ISSUE THREAD

**Issue by limboc** [north2016/T-MVP#1]
是否可以把presenter层从ui里独立出来，毕竟不同的view可能有相同的业务

**Comment by north2014** [comment]
可以  我这是按照功能分包  也可以按照结构分包

**Comment by Ztiany** [comment]
Presenter大多数的时候都是为了解耦，很少看到能复用的Presenter，比较赞成作者的分包方式，但是我觉得不应该把M和P绑定在一起，很多时候一个Presenter需要跟多个数据源（多个M）交互。所以每个M应该是独立的，由上层的Presenter来调用一个或者多个。
