### ISSUE TITLE
提一个问题啊，

### ISSUE THREAD

**Issue by jackxieweiwu** [north2016/T-MVP#14]
为什么我clone了项目  到如as中  出现了这样的错误   Error:(53, 1) A problem occurred evaluating project ':app'.
> Could not get unknown property 'com' for project ':app' of type org.gradle.api.Project.      但是在windows下确没有这样的错误，但是在ubuntu下却存在这样的错误，这是为什么呢？

**Comment by north2016** [comment]
这里的com仅仅是测试用的过滤包名用的    难道ubuntu下文件路径与其它有什么异常？

**Comment by jackxieweiwu** [comment]
文件路径是没有问题的，没有任何中文，而且文件的权限是都是可读可写的。

**Comment by jackxieweiwu** [comment]
出错的原因就是 apply plugin: com.app.plugin.AspectjPlugin    apply plugin: com.app.plugin.JavassistPlugin的原因。

**Comment by jackxieweiwu** [comment]
这个gradle plugin无法被主项目的gradle识别，？？？？？？

**Comment by jp1017** [comment]
什么意思，贴一贴gradle看看什么鬼 @jackxieweiwu

**Comment by north2016** [comment]
buildsrc没有被识别？

**Comment by jackxieweiwu** [comment]
是的  buildsrc 没有被识别，还有就是在运行的时候，apt无法自动生成代码！

**Comment by north2016** [comment]
你的AS是2.2.2的吗？

**Comment by jackxieweiwu** [comment]
是  2.2.3的

**Comment by north2016** [comment]
为兼容linux、ubuntu等系统，运行之前需要发布插件到本地

修改点

　　1.修改maven为本地目录 app build.gradle:

         maven{
            url uri('file:/Users/baixiaokang/Documents/repo/')//改为你本地的仓库地址
          }
buildsrc build.gradle:

        uploadArchives {
            repositories.mavenDeployer {
                repository(url: 'file:/Users/baixiaokang/Documents/repo/')//改为你本地的仓库地址
                pom.groupId = 'com.app.plugin'
                pom.artifactId ='gradleplugin'
                pom.version = '1.0.0'
            }
        }        

　　2.运行 ./gradlew -p buildsrc clean build uploadArchives --info
