### ISSUE TITLE
Build error issue

### ISSUE THREAD

**Issue by jinghongjun** [north2016/T-MVP#17]
需要把app工程下build.gradle文件中
apply plugin: com.app.plugin.AspectjPlugin
apply plugin: com.app.plugin.JavassistPlugin
移除，才可以编译通过。

**Comment by jp1017** [comment]
感谢，遇到同样issue

**Comment by north2016** [comment]
大哥  你把这俩移除   你进去不黑屏才怪啊

**Comment by north2016** [comment]
请检查  as版本 gradle版本 buildTools版本
