### ISSUE TITLE
运行黑屏？

### ISSUE THREAD

**Issue by jp1017** [north2016/T-MVP#18]
一直打印这个log：

```
01-12 13:19:27.155 755-1678/cn.com.app I/SurfaceView: Locking canvas... stopped=false, win=android.view.SurfaceView$MyWindow@5b73d5d
01-12 13:19:27.155 755-1678/cn.com.app I/SurfaceView: Returned canvas: android.view.Surface$CompatibleCanvas@16a5a6d2
```

并且黑屏：

<img src=https://cloud.githubusercontent.com/assets/7868514/21878016/2cf4d35c-d8ca-11e6-868f-845bb976d80a.jpg width="260"/>

**Comment by north2016** [comment]
没遇到过   报手机版本型号

**Comment by north2016** [comment]
apply plugin: com.app.plugin.AspectjPlugin
apply plugin: com.app.plugin.JavassistPlugin

大哥  你把这俩移除   你进去不黑屏才怪啊

**Comment by north2016** [comment]
如果报错   肯定是as版本  gradle版本  buildTools版本   有问题

**Comment by jp1017** [comment]
@north2016 别着急关啊, 

这两个插件找不到:

>Error:Could not get unknown property 'com' for project ':app' of type org.gradle.api.Project.

as: 2.2.3, gradle:3.2.1 buildTools: 24.0.3

**Comment by north2016** [comment]
as:2.2.2    grade:2.2.3       buildTools:24.0.3

**Comment by jp1017** [comment]
不应该是这个问题，ubuntu的问题，好多同学有这个issue？ :cry:

**Comment by north2016** [comment]
我用的是本地的插件。未发布状态。
有可能你的电脑系统不能识别，但是发布出去肯定是能识别的
gradle插件发布到本地：

http://kvh.io/cn/embrace-android-studio-gradle-plugin.html

看这篇博客

**Comment by jp1017** [comment]
windows下是正常的，，，ubuntu不行。。。

**Comment by north2016** [comment]
运行之前需要修改点
　　1.修改gradle.properties文件中的PLUGIN_URL值为本地目录
　　2.运行 ./gradlew -p buildsrc clean build uploadArchives --info
