### ISSUE TITLE
编译报错，求解决

### ISSUE THREAD

**Issue by yswheye** [north2016/T-MVP#19]
Error:Could not get unknown property 'com' for project ':app' of type org.gradle.api.Project.

**Comment by yswheye** [comment]
看了其他的issues，我的环境是ubuntu，看到其他人也遇到了。这个怎么解决？

**Comment by north2016** [comment]
ubuntu...没用过啊

**Comment by north2016** [comment]
估计是插件识别不出来

**Comment by north2016** [comment]
我用的是本地的插件。未发布状态。
有可能你的电脑系统不能识别，但是发布出去肯定是能识别的
gradle插件发布到本地：

http://kvh.io/cn/embrace-android-studio-gradle-plugin.html

看这篇博客

**Comment by north2016** [comment]
运行之前需要修改点
　　1.修改gradle.properties文件中的PLUGIN_URL值为本地目录
　　2.运行 ./gradlew -p buildsrc clean build uploadArchives --info
