### ISSUE TITLE
关于javassist和Aspect的一点问题

### ISSUE THREAD

**Issue by striveprince** [north2016/T-MVP#21]
1.lambda表达式为什么无法在@Aspect注解下的类下使用？
2.javassist代码中的是.class文件，就是说可以使用java，但是你这边用的是groovy。为什么不使用java呢？

**Comment by north2016** [comment]
1、AspectJ和Retrolambda插件是在同一编译期  顺序原因导致无法兼容  不过这并无大碍  
2、只是以groovy作为后缀，里面的代码其实是java（groovy兼容java），只是用了少数的groovy的语法和关键字
