### ISSUE TITLE
找不到文件

### ISSUE THREAD

**Issue by Sum41forever** [north2016/T-MVP#23]
弄了很多次，重新从Github上下了dmeo也不能运行 

import com.apt.TRouter; 这个找不到，看Issues里面也没有其他人遇到这种问题

是要改什么东西么 
distributionUrl=https\://services.gradle.org/distributions/gradle-**2.14.1**-all.zip
build:gradle:**2.2.2**

![123](https://cloud.githubusercontent.com/assets/18468976/22821450/11eb71a8-efb6-11e6-8224-bc78166191e5.png)

**Comment by Sum41forever** [comment]
F:\AppSpace\T-MVP-master\app\src\main\java\com\ui\release\releaseContract.java
Error:(10, 8) 错误: 类ReleaseContract是公共的, 应在名为 ReleaseContract.java 的文件中声明
F:\AppSpace\T-MVP-master\app\src\main\java\com\ui\advise\AdviseActivity.java
Error:(15, 31) 错误: 程序包com.ui.main.databinding不存在
Error:(18, 67) 错误: 找不到符号
符号: 类 ActivityFeedbackBinding
F:\AppSpace\T-MVP-master\app\src\main\java\com\ui\article\ArticleActivity.java
Error:(19, 31) 错误: 程序包com.ui.main.databinding不存在
Error:(22, 69) 错误: 找不到符号
符号: 类 ActivityDetailBinding
F:\AppSpace\T-MVP-master\app\src\main\java\com\ui\login\LoginActivity.java
Error:(13, 31) 错误: 程序包com.ui.main.databinding不存在
Error:(20, 65) 错误: 找不到符号
符号: 类 ActivityLoginBinding
F:\AppSpace\T-MVP-master\app\src\main\java\com\ui\release\ReleaseActivity.java
Error:(12, 31) 错误: 程序包com.ui.main.databinding不存在
Error:(16, 69) 错误: 找不到符号
符号: 类 ActivityReleaseBinding
F:\AppSpace\T-MVP-master\app\src\main\java\com\ui\user\UserActivity.java
Error:(22, 31) 错误: 程序包com.ui.main.databinding不存在
Error:(27, 63) 错误: 找不到符号
符号: 类 ActivityUserBinding
F:\AppSpace\T-MVP-master\app\src\main\java\com\aop\CheckLoginAspect.java
Error:(8, 15) 错误: 程序包com.apt不存在
Error:(36, 29) 错误: 找不到符号
符号: 变量 TRouter
F:\AppSpace\T-MVP-master\app\src\main\java\com\base\adapter\CoreAdapter.java
Error:(10, 19) 错误: 找不到符号
符号:   类 BR
位置: 程序包 com.ui.main
Error:(34, 45) 错误: 找不到符号
符号:   变量 BR
位置: 类 CoreAdapter<M>
其中, M是类型变量:
M扩展已在类 CoreAdapter中声明的Object
F:\AppSpace\T-MVP-master\app\src\main\java\com\base\DataBindingActivity.java
Error:(15, 15) 错误: 程序包com.apt不存在
Error:(33, 9) 错误: 找不到符号
符号:   变量 TRouter
位置: 类 DataBindingActivity<B>
其中, B是类型变量:
B扩展已在类 DataBindingActivity中声明的ViewDataBinding
F:\AppSpace\T-MVP-master\app\src\main\java\com\ui\home\ArticleFragment.java
Error:(14, 15) 错误: 程序包com.apt不存在
Error:(50, 35) 错误: 找不到符号
符号:   变量 ApiFactory
位置: 类 ArticleFragment
F:\AppSpace\T-MVP-master\app\src\main\java\com\base\util\helper\RouterHelper.java
Error:(6, 15) 错误: 程序包com.apt不存在
Error:(18, 9) 错误: 找不到符号
符号:   变量 TRouter
位置: 类 RouterHelper
F:\AppSpace\T-MVP-master\app\src\main\java\com\base\util\InstanceUtil.java
Error:(4, 15) 错误: 程序包com.apt不存在
Error:(21, 24) 错误: 找不到符号
符号:   变量 InstanceFactory
位置: 类 InstanceUtil
F:\AppSpace\T-MVP-master\app\src\main\java\com\ui\advise\AdvisePresenter.java
Error:(7, 15) 错误: 程序包com.apt不存在
Error:(23, 9) 错误: 找不到符号
符号:   变量 ApiFactory
位置: 类 AdvisePresenter
Error:(36, 35) 错误: 找不到符号
符号:   变量 ApiFactory
位置: 类 AdvisePresenter
F:\AppSpace\T-MVP-master\app\src\main\java\com\ui\article\ArticlePresenter.java
Error:(8, 15) 错误: 程序包com.apt不存在
Error:(27, 17) 错误: 找不到符号
符号:   变量 ApiFactory
位置: 类 ArticlePresenter
Error:(44, 35) 错误: 找不到符号
符号:   变量 ApiFactory
位置: 类 ArticlePresenter
F:\AppSpace\T-MVP-master\app\src\main\java\com\ui\home\HomeActivity.java
Error:(16, 15) 错误: 程序包com.apt不存在
Error:(26, 31) 错误: 程序包com.ui.main.databinding不存在
Error:(31, 63) 错误: 找不到符号
符号: 类 ActivityMainBinding
Error:(52, 55) 错误: 找不到符号
符号:   变量 TRouter
位置: 类 HomeActivity
Error:(53, 60) 错误: 找不到符号
符号:   变量 TRouter
位置: 类 HomeActivity
Error:(95, 50) 错误: 找不到符号
符号:   变量 TRouter
位置: 类 HomeActivity
Error:(96, 54) 错误: 找不到符号
符号:   变量 TRouter
位置: 类 HomeActivity
Error:(105, 17) 错误: 找不到符号
符号:   变量 TRouter
位置: 类 HomeActivity
Error:(108, 17) 错误: 找不到符号
符号:   变量 TRouter
位置: 类 HomeActivity
F:\AppSpace\T-MVP-master\app\src\main\java\com\ui\login\LoginPresenter.java
Error:(5, 15) 错误: 程序包com.apt不存在
Error:(19, 17) 错误: 找不到符号
符号:   变量 ApiFactory
位置: 类 LoginPresenter
Error:(31, 17) 错误: 找不到符号
符号:   变量 ApiFactory
位置: 类 LoginPresenter
F:\AppSpace\T-MVP-master\app\src\main\java\com\ui\main\AboutActivity.java
Error:(6, 15) 错误: 程序包com.apt不存在
Error:(8, 31) 错误: 程序包com.ui.main.databinding不存在
Error:(15, 56) 错误: 找不到符号
符号: 类 ActivityAboutBinding
Error:(30, 35) 错误: 找不到符号
符号:   变量 ApiFactory
位置: 类 AboutActivity
F:\AppSpace\T-MVP-master\app\src\main\java\com\ui\main\FlashActivity.java
Error:(8, 15) 错误: 程序包com.apt不存在
Error:(12, 31) 错误: 程序包com.ui.main.databinding不存在
Error:(17, 56) 错误: 找不到符号
符号: 类 ActivityFlashBinding
Error:(40, 9) 错误: 找不到符号
符号:   变量 TRouter
位置: 类 FlashActivity
F:\AppSpace\T-MVP-master\app\src\main\java\com\ui\release\ReleasePresenter.java
Error:(8, 15) 错误: 程序包com.apt不存在
Error:(36, 25) 错误: 找不到符号
符号: 变量 ApiFactory
F:\AppSpace\T-MVP-master\app\src\main\java\com\ui\user\UserPresenter.java
Error:(10, 15) 错误: 程序包com.apt不存在
Error:(34, 17) 错误: 找不到符号
符号:   变量 ApiFactory
位置: 类 UserPresenter
Error:(46, 17) 错误: 找不到符号
符号:   变量 ApiFactory
位置: 类 UserPresenter
Error:(61, 44) 错误: 找不到符号
符号:   变量 ApiFactory
位置: 类 UserPresenter

**Comment by north2016** [comment]
这都类都是apt自动生成的   直接build  run 就可以了

**Comment by north2016** [comment]
如果还不行  就是as缓存的bug    需要 删build文件夹  清缓存  重启  即可

**Comment by Penny7088** [comment]
请问你是怎么解决的

**Comment by TMLAndroid** [comment]
一样找不到文件的错误.......
错误日志如下：
Error:Execution failed for task ':app:compileDebugJavaWithJavac'.
> java.lang.RuntimeException: failure, see logs for details.
  cannot generate view binders com.sun.tools.javac.code.Symbol$CompletionFailure: 找不到android.view.View$InvalidateInfo的类文件

**Comment by TMLAndroid** [comment]
参考这个，好像是Android Studio 2.3 版本会出现这种问题  https://stackoverflow.com/questions/42583759/databinding-not-working-after-upgrade-android-studio-2-3  @Sum41forever @Penny7088

**Comment by TMLAndroid** [comment]
参考这个，好像是Android Studio 2.3 版本会出现这种问题  https://stackoverflow.com/questions/42583759/databinding-not-working-after-upgrade-android-studio-2-3  @Sum41forever @Penny7088
