### ISSUE TITLE
文件命名错误导致编译不通过，

### ISSUE THREAD

**Issue by Sum41forever** [north2016/T-MVP#24]
还是昨天那个不能自动生成代码的问题。
经过排查，是有个类的命名错误了。见图

com.ui.release包下面的ReleaseContract这个类，写成了小写开头

![123](https://cloud.githubusercontent.com/assets/18468976/22850555/44bd0e26-f046-11e6-9eda-56e8df2d2348.png)

**Comment by north2016** [comment]
本地是大写的，github出BUG了？

**Comment by north2016** [comment]
反复确认过  本地就是大写的  莫名其妙变小写
