### ISSUE TITLE
API 怎么支持多个BaseUrl

### ISSUE THREAD

**Issue by zacharyzzc** [north2016/T-MVP#31]
现在Api 这个类里面写上了BaseUrl，就只能用这个域名下的接口，当有第三方的接口地址，就无法使用了APT自动生成的代码了
还有一个问题，我能否拆分出多个ApiService这样的类，现在全部的接口都在ApiService里面唉，有点太多了一个类
求大大回复，谢谢

**Comment by north2016** [comment]
当然可以 给ApiFactory注解加个BaseUrl的参数  这样把BaseUrl通过注解传进去  第三方的借口可以单独写ApiService  然后apt一次处理多个ApiService  生成一个ApiFactory
