### ISSUE TITLE
aop在debug上起作用  release上失效

### ISSUE THREAD

**Issue by CentForever** [north2016/T-MVP#32]

**Comment by north2016** [comment]
aop注解的相关类需要防混淆

**Comment by north2016** [comment]
方法一：针对自己的注解在混淆文件里keep  ，只适用于注解aop的方式
方法二：使用@Keep注解，在proguard-rules.pro配置文件中加入以下规则

-dontskipnonpubliclibraryclassmembers
-printconfiguration
-keep,allowobfuscation @interface android.support.annotation.Keep

-keep @android.support.annotation.Keep class *
-keepclassmembers class * {
    @android.support.annotation.Keep *;
}
哪里有aop @Keep哪里
