### ISSUE TITLE
程序编译不成功

### ISSUE THREAD

**Issue by OptimusMX** [north2016/T-MVP#36]
提示缺少资源文件

**Comment by lhzlg3368** [comment]
Me to

**Comment by lhzlg3368** [comment]
Warning:One of the plugins you are using supports Java 8 language features. To try the support built into the Android plugin, remove the following from your build.gradle:
    apply plugin: 'me.tatarka.retrolambda'
To learn more, go to https://d.android.com/r/tools/java-8-support-message.html

**Comment by michaelzhang1994** [comment]
一样

**Comment by north2016** [comment]
@lhzlg3368 提示都这么明显了  不会改一下吗  Java 8  删掉  apply plugin: 'me.tatarka.retrolambda'
