### ISSUE TITLE
分页加载时，如果第一屏加载的条目没有占满一屏，则footer一直显示正在加载

### ISSUE THREAD

**Issue by liangjianqi** [north2016/T-MVP#5]

**Comment by north2014** [comment]
你debug一下看有没有走 this.isHasMore = datas.size() >= C.PAGE_COUNT;这一句
（这类问题进群问我好啦）

**Comment by liangjianqi** [comment]
执行了，demo里面我改小C.PAGE_COUNT也是这个情况，群里直接咨询，3Q
